### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by stefanhusmann** [vodik/repose#33] opened 2016-04-10 18:30 UTC
Under i686 architecture:
'''
==> Making package: repose 5-1 (So 10. Apr 20:17:52 CEST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found 5.tar.gz
==> Validating source files with sha1sums...
    5.tar.gz ... Passed
==> Extracting sources...
  -> Extracting 5.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make: Entering directory '/home/haawda/paketierung/repose/src/repose-5'
cc -std=c11 -g -Wall -Wextra -pedantic -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wno-missing-field-initializers -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DREPOSE_VERSION=\"2\" -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2  -c -o package.o src/package.c
In file included from src/package.c:14:0:
src/package.c: In function 'pkginfo_assignment':
src/util.h:36:36: error: '_Generic' selector of type 'unsigned int' is not compatible with any association
 #define fromstr(str, out) _Generic((*out), long: xstrtol, unsigned long: xstrtoul)(str, out)
                                    ^
src/package.c:36:9: note: in expansion of macro 'fromstr'
         fromstr(value, &pkg->isize);
         ^
<builtin>: recipe for target 'package.o' failed
make: *** [package.o] Error 1
make: Leaving directory '/home/haawda/paketierung/repose/src/repose-5'
==> ERROR: A failure occurred in build().
    Aborting...
'''

**Comment by vodik** [comment] 2016-04-11 15:47
Are you building an old version of repose? This looks like something that's already been fixed. `fromstr` looks like this now:

~~~c
#define fromstr(str, out) _Generic((*out), \
    size_t: str_to_size, \
    time_t: str_to_time)(str, out)
~~~

Which was fixed in 1bec319d5f04a952c7db4e5bac2b9b45f504b6e2.

**Comment by vodik** [comment] 2016-04-11 15:49
Yeah, I'm pretty sure that fix was actually for the exact same issue, someone reported it on #archlinux. Because `size_t` is platform dependent and I wrongly wrote code assuming it'll be an `unsigned long`.

**Comment by vodik** [comment] 2016-04-11 15:56
Yeah, I just noticed the v5 in your output. Yeah, this is something that's been fixed. I can reproduce it building v5 but not on master.

I think it's about time to release v6.

**Closed by vodik** 2016-04-11 15:56 UTC
